# Generated by Django 2.2 on 2020-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='complited',
            field=models.BooleanField(blank=True, null=True, verbose_name='Завершено'),
        ),
    ]
