# Generated by Django 2.2 on 2020-11-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prompt_complited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='added_users',
            field=models.ManyToManyField(blank=True, related_name='added_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
