# Generated by Django 2.2 on 2020-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201106_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='complited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='done_date_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выполнения'),
        ),
    ]
