# Generated by Django 2.2 on 2020-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201106_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profiles/avatar.png', null=True, upload_to='images/profiles', verbose_name='Фотография'),
        ),
    ]
